[package]
name = "uefi-hello-world"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "bootx64"
path = "src/main.rs"

[dependencies]
uefi = { version = "0.14.0", features = ["exts", "logger"] }
uefi-services = "0.11.0"
log = { version = "0.4.14", default-features = false }
